# Generated by Django 4.2.11 on 2024-03-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="city",
            table="city",
        ),
        migrations.AlterModelTable(
            name="continent",
            table="continent",
        ),
        migrations.AlterModelTable(
            name="country",
            table="country",
        ),
        migrations.AlterModelTable(
            name="poi",
            table="poi",
        ),
        migrations.AlterModelTable(
            name="poidetails",
            table="poiDetails",
        ),
        migrations.AlterModelTable(
            name="poitype",
            table="poiType",
        ),
        migrations.AlterModelTable(
            name="tour",
            table="tour",
        ),
        migrations.AlterModelTable(
            name="tourpoi",
            table="tourPoi",
        ),
        migrations.AlterModelTable(
            name="tourusers",
            table="tourUsers",
        ),
    ]
